{"name": "Ошибка при авторизации с неверным логином", "status": "passed", "start": 1719933807393, "stop": 1719933807857, "uuid": "15fb706a-1fab-489c-94df-3119227fc20a", "historyId": "36c490236660942a89313446ee570a2f", "testCaseId": "36c490236660942a89313446ee570a2f", "fullName": "tests.test_login.TestLogin#test_login_bad_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "MacBook-Pro-Ula.local"}, {"name": "thread", "value": "8671-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}