{"name": "Ошибка при авторизации с неверными данными", "status": "passed", "start": 1719934906388, "stop": 1719934906543, "uuid": "0039cbfb-5ca0-4263-aa68-7f43a019f643", "historyId": "34b80ad7b677f554cd1d749edb7b082e", "testCaseId": "34b80ad7b677f554cd1d749edb7b082e", "fullName": "tests.test_login.TestLogin#test_login_invalid_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "MacBook-Pro-Ula.local"}, {"name": "thread", "value": "8866-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}